# Generated by Django 5.2 on 2025-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clt_image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
