# Generated by Django 5.2 on 2025-04-28 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_cpassword_userapp_stu_cpassword_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_cpassword',
            new_name='user_cpassword',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_detail',
            new_name='user_detail',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_dob',
            new_name='user_dob',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_gender',
            new_name='user_gender',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_image',
            new_name='user_image',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_password',
            new_name='user_password',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_phone',
            new_name='user_phone',
        ),
        migrations.RenameField(
            model_name='userapp',
            old_name='stu_username',
            new_name='user_username',
        ),
    ]
