# Generated by Django 5.2 on 2025-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_client_clt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_image', models.ImageField(upload_to='image/')),
                ('room_name', models.CharField(max_length=30)),
                ('room_price', models.IntegerField()),
                ('room_info', models.CharField(max_length=20)),
            ],
        ),
    ]
