# Generated by Django 5.2 on 2025-04-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.baseinfo')),
                ('Deparment', models.CharField(max_length=50)),
                ('Salary', models.IntegerField()),
            ],
            bases=('app.baseinfo',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.baseinfo')),
                ('branch', models.CharField(max_length=50)),
                ('fees', models.IntegerField()),
            ],
            bases=('app.baseinfo',),
        ),
    ]
