# Generated by Django 5.2 on 2025-04-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_email', models.EmailField(max_length=254, unique=True)),
                ('stu_contact', models.IntegerField()),
                ('stu_city', models.CharField(max_length=100)),
            ],
        ),
    ]
