# Generated by Django 5.2 on 2025-04-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_phone', models.IntegerField()),
                ('user_dob', models.DateField()),
                ('user_gender', models.CharField(max_length=10)),
                ('user_image', models.ImageField(upload_to='image/')),
                ('user_detail', models.CharField(max_length=100)),
                ('user_password', models.CharField(max_length=20)),
                ('user_cpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
