# Generated by Django 5.2 on 2025-04-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_stu_cpassword_userapp_user_cpassword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clt_username', models.CharField(max_length=50)),
                ('clt_email', models.EmailField(max_length=254, unique=True)),
                ('clt_phone', models.IntegerField()),
                ('clt_dob', models.DateField()),
                ('clt_gender', models.CharField(max_length=10)),
                ('clt_image', models.ImageField(upload_to='image/')),
                ('clt_detail', models.CharField(max_length=100)),
                ('clt_password', models.CharField(max_length=20)),
                ('clt_cpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='UserApp',
        ),
    ]
