# Generated by Django 5.2 on 2025-05-01 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='adharno',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='aadhar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.aadhar', to_field='adharno'),
        ),
    ]
