# Generated by Django 5.2 on 2025-05-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_clt_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clt_image',
            field=models.ImageField(upload_to='image/'),
        ),
    ]
