# Generated by Django 5.2 on 2025-04-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_student_stu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stu_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
