# Generated by Django 5.2 on 2025-04-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_stu_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stu_name',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='Ajay Chnadravanshi', max_length=100),
        ),
    ]
