# Generated by Django 5.2 on 2025-04-22 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_student_stu_name_student_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='stu_name',
        ),
    ]
